# Generated by Django 5.0.6 on 2024-05-31 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="post",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.post",
            ),
            preserve_default=False,
        ),
    ]
