# Generated by Django 5.0.6 on 2024-05-31 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_rename_approve_comments_approved"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comments",
            options={"ordering": ["-created_date"]},
        ),
    ]
