# Generated by Django 5.0.6 on 2024-06-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_alter_comments_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="login_required",
            field=models.BooleanField(default=False),
        ),
    ]
